### ISSUE TITLE
Need help with using this package.

### ISSUE THREAD

**Issue by NavDeol13** [shmokmt/app-store-connect-client#16]
Hii

After installing this package. I got the following error while trying to use this package. 

>>> client = app_store.Client(username, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NKDeol\AppData\Local\Programs\Python\Python39\lib\site-packages\app_store_connect_client\analytics.py", line 30, in __init__
    self._login(username, password)
  File "C:\Users\NKDeol\AppData\Local\Programs\Python\Python39\lib\site-packages\app_store_connect_client\analytics.py", line 74, in _login
    raise Exception(
Exception: There was a problem with loading the login page cookies. Check login credentials.

Please help me in resolving this issue..

Thanks in advance

**Comment by wiloaguilar** [comment]
i have the same issue...
